/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author alumno
 */
public class Juego extends javax.swing.JFrame {

    /**
     * Es un juego en el que pones que cantidad de numeros quieres generar y luego te dice cual es de todos el menor y le mayor
     */
    public Juego() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtMostrar = new javax.swing.JTextArea();
        jbCrea = new javax.swing.JButton();
        jl1 = new javax.swing.JLabel();
        jtEntra = new javax.swing.JTextField();
        bInicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jtMostrar.setEditable(false);
        jtMostrar.setColumns(20);
        jtMostrar.setRows(5);
        jScrollPane1.setViewportView(jtMostrar);

        jbCrea.setText("crea");
        jbCrea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCreaActionPerformed(evt);
            }
        });

        jl1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl1.setText("nombres d'enters a crear");

        jtEntra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtEntraActionPerformed(evt);
            }
        });

        bInicio.setText("Inicio");
        bInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jl1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtEntra, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbCrea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bInicio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtEntra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbCrea)
                        .addComponent(bInicio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtEntraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtEntraActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jtEntraActionPerformed

    private void jbCreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCreaActionPerformed
        // TODO add your handling code here:
        int nEnters = Integer.parseInt(jtEntra.getText());
        // int [] matriu=opmliAmbAleatori(nEnters);

        if (nEnters > 1) {
            int[] matriu = new int[nEnters];
            opmliAmbAleatori(matriu);
            mostra(matriu);
            mostraMaxMin(matriu);

        }
    }//GEN-LAST:event_jbCreaActionPerformed
/**
 * 
 * @param evt A la X te sale un mensaje para que confirmes si quieres cerrar el proyecto
 */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        cerrar();
    }//GEN-LAST:event_formWindowClosing
/**
 * 
 * @param evt Con este botón vuelves al formulario del inicio
 */
    private void bInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicioActionPerformed
        // TODO add your handling code here:
         new FPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bInicio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCrea;
    private javax.swing.JLabel jl1;
    private javax.swing.JTextField jtEntra;
    private javax.swing.JTextArea jtMostrar;
    // End of variables declaration//GEN-END:variables

    private void opmliAmbAleatori(int[] matriu) {
        for (int i = 0; i < matriu.length; i++) {
            matriu[i] = getAleatori(100, 150);
        }
    }

    private int getAleatori(int inf, int sup) {
        if (inf > sup) {
            return getAleatori(sup, inf);
        }
        return inf + (int) (Math.random() * (sup - inf + 1));
    }

    private void mostra(int[] matriu) {
        String cad = "";
        for (int i = 0; i < matriu.length; i++) {
            cad += matriu[i];
            cad += (i + 1) % 10 == 0 ? "\n" : " ";//salto de linea cada 10 enteros
        }
        jtMostrar.setText(cad);
    }

    private void mostraMaxMin(int[] matriu) {
        int iMax = 0;
        int iMin = 0;
        for (int i = 0; i < matriu.length; i++) {
            if (matriu[i] > matriu[iMax]) {
                iMax = i;
            }
            if (matriu[i] < matriu[iMin]) {
                iMin = i;
            }
        }
        jtMostrar.append(String.format("\n el menor és %d i esta en l'index %d", matriu[iMin], iMin));
        jtMostrar.append(String.format(" \n el major és %d i esta en l'index %d", matriu[iMax], iMax));

    }

    public void cerrar() {
        Object[] opciones = {"Aceptar", "Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(rootPane, "En realidad desea realizar cerrar la aplicacion", "Mensaje de Confirmacion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, opciones, "Aceptar");
        if (eleccion == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {
        }
    }
}
